// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8F1mFkqs6OfdUw5uzpsVQGRqtL938RCo',
    appId: '1:808369467122:web:0b4830ce3ea79d7d412a6b',
    messagingSenderId: '808369467122',
    projectId: 'production-tracker-top',
    authDomain: 'production-tracker-top.firebaseapp.com',
    storageBucket: 'production-tracker-top.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjZ4mPz3BVc0bPLlNGVFeD387Iy1g_Stg',
    appId: '1:808369467122:android:82e9e1a6992ff4bd412a6b',
    messagingSenderId: '808369467122',
    projectId: 'production-tracker-top',
    storageBucket: 'production-tracker-top.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAsfydZLUR__9j2H2F-wmTq6W7EuMZMsM',
    appId: '1:808369467122:ios:bdabf1bdbe1b5292412a6b',
    messagingSenderId: '808369467122',
    projectId: 'production-tracker-top',
    storageBucket: 'production-tracker-top.firebasestorage.app',
    iosBundleId: 'com.example.productionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAsfydZLUR__9j2H2F-wmTq6W7EuMZMsM',
    appId: '1:808369467122:ios:bdabf1bdbe1b5292412a6b',
    messagingSenderId: '808369467122',
    projectId: 'production-tracker-top',
    storageBucket: 'production-tracker-top.firebasestorage.app',
    iosBundleId: 'com.example.productionTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8F1mFkqs6OfdUw5uzpsVQGRqtL938RCo',
    appId: '1:808369467122:web:8c2158658670431e412a6b',
    messagingSenderId: '808369467122',
    projectId: 'production-tracker-top',
    authDomain: 'production-tracker-top.firebaseapp.com',
    storageBucket: 'production-tracker-top.firebasestorage.app',
  );
}
